"""Dataclass DTOs — the API models of stapel-docs (never ORM instances).

Model-backed DTOs are generated by presenters based on
``stapel_core.django.api.presenters.Presenter`` (declares model/fields and
generates the DTO dataclass and serializer); hand-written dataclasses here
are for shapes with no single backing model (envelopes, upload tickets).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class SaveResultDTO:
    """Outcome of an accepted content save (PUT content / revision restore)."""

    head_seq: int
    revision_id: Optional[str] = None


@dataclass
class JournalUpdateDTO:
    """One journal row of the ``?since=`` replay feed."""

    seq: int
    payload: str  # base64
    author_id: Optional[str]
    created_at: str


@dataclass
class UpdatesFeedDTO:
    """Replay feed answer for ``GET .../updates?since=``."""

    head_seq: int
    updates: List[JournalUpdateDTO] = field(default_factory=list)


@dataclass
class ResyncDTO:
    """``since`` fell out of the compaction window — rehydrate via snapshot."""

    resync: bool
    head_seq: int
    snapshot_seq: int


@dataclass
class AppendResultDTO:
    """Outcome of a journal append batch."""

    head_seq: int


@dataclass
class DownloadUrlDTO:
    """Opaque presigned GET URL — clients must never assume its shape."""

    url: str


@dataclass
class UploadTicketDTO:
    """Pending direct-to-storage upload: the document row exists already
    (hidden from listings) and ``put_url`` is the presigned PUT target.

    ``expires_at`` is the instant the ticket stops being spendable (null
    only when the host disabled the TTL) — a client that cannot see the
    deadline cannot honour it."""

    upload_id: str
    document_id: str
    key: str
    put_url: str
    expires_at: Optional[str] = None


@dataclass
class TrashPurgeResultDTO:
    """Counts of irreversibly purged trash items."""

    folders: int
    documents: int


@dataclass
class BreadcrumbNodeDTO:
    """One ancestor folder on a search hit's path."""

    id: str
    name: str


@dataclass
class SearchHitDTO:
    """One name-search hit (drive-spec §3.3).

    ``kind`` dispatches the client's rendering; ``breadcrumb`` is the
    root-first ancestor chain of the hit's CONTAINER (empty at the workspace
    root), materialized server-side so a result list costs one request.
    """

    kind: str
    id: str
    workspace_id: str
    name: str
    parent_id: Optional[str] = None
    type: Optional[str] = None
    is_starred: Optional[bool] = None
    breadcrumb: List[BreadcrumbNodeDTO] = field(default_factory=list)


@dataclass
class SharedDocumentDTO:
    """What a link BEARER sees: the document, and nothing around it.

    The stripped envelope of axis §6 — no workspace, no folder, no owner,
    no star state, no revision history. A link grants a document, not a
    seat: anything that would let the holder infer the shape of the
    workspace (its tree, who is in it, what else it contains) is deliberately
    absent, and history is absent besides, because an old revision can hold
    text that was deleted on purpose since.

    ``level`` is what the presenter may DO with it, so a client can render
    a read-only editor without guessing from a 403 it has not hit yet.
    """

    id: str
    type: str
    title: str
    head_seq: int
    size_bytes: int
    mime_type: str
    editor_hint: str
    collab: str
    diffable: bool
    level: str
    updated_at: str
