"""Dataclass DTOs — the API models of stapel-docs (never ORM instances).

Model-backed DTOs are generated by presenters based on
``stapel_core.django.api.presenters.Presenter`` (declares model/fields and
generates the DTO dataclass and serializer); hand-written dataclasses here
are for shapes with no single backing model (envelopes, upload tickets).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class SaveResultDTO:
    """Outcome of an accepted content save (PUT content / revision restore)."""

    head_seq: int
    revision_id: Optional[str] = None


@dataclass
class JournalUpdateDTO:
    """One journal row of the ``?since=`` replay feed."""

    seq: int
    payload: str  # base64
    author_id: Optional[str]
    created_at: str


@dataclass
class UpdatesFeedDTO:
    """Replay feed answer for ``GET .../updates?since=``."""

    head_seq: int
    updates: List[JournalUpdateDTO] = field(default_factory=list)


@dataclass
class ResyncDTO:
    """``since`` fell out of the compaction window — rehydrate via snapshot."""

    resync: bool
    head_seq: int
    snapshot_seq: int


@dataclass
class AppendResultDTO:
    """Outcome of a journal append batch."""

    head_seq: int


@dataclass
class DownloadUrlDTO:
    """Opaque presigned GET URL — clients must never assume its shape."""

    url: str


@dataclass
class UploadTicketDTO:
    """Pending direct-to-storage upload: the document row exists already
    (hidden from listings) and ``put_url`` is the presigned PUT target."""

    upload_id: str
    document_id: str
    key: str
    put_url: str


@dataclass
class TrashPurgeResultDTO:
    """Counts of irreversibly purged trash items."""

    folders: int
    documents: int
