"""Dataclass DTOs — the API models of stapel-docs (never ORM instances).

Model-backed DTOs are generated by presenters based on
``stapel_core.django.api.presenters.Presenter`` (declares model/fields and
generates the DTO dataclass and serializer); hand-written dataclasses here
are for shapes with no single backing model (envelopes, upload tickets).
"""
