"""Serializers for the stapel-docs API.

Model-backed response serializers are generated by the presenters
(``stapel_core.django.api.presenters.Presenter``); request serializers and
non-model envelopes live here.
"""
