"""Serializers for the stapel-docs API.

Model-backed response serializers are generated by the presenters
(``stapel_core.django.api.presenters.Presenter``); request serializers and
non-model envelopes live here.

The module-level ``FolderSerializer``/``DocumentSerializer``/
``RevisionSerializer`` names resolve the ACTIVE presenter once at import
time — a ``STAPEL_SWAP`` override lands in both the schema and the runtime
because settings are fixed before this module loads.
"""
from __future__ import annotations

import base64

from rest_framework import serializers
from stapel_core.django.api.serializers import StapelDataclassSerializer

from .dto import (
    AppendResultDTO,
    DownloadUrlDTO,
    ResyncDTO,
    SaveResultDTO,
    TrashPurgeResultDTO,
    UpdatesFeedDTO,
    UploadTicketDTO,
)
from .presenters import (
    get_document_presenter,
    get_folder_presenter,
    get_revision_presenter,
)

FolderSerializer = get_folder_presenter().serializer_class()
DocumentSerializer = get_document_presenter().serializer_class()
RevisionSerializer = get_revision_presenter().serializer_class()


# ── Envelope responses ───────────────────────────────────────────────


class SaveResultSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = SaveResultDTO


class AppendResultSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = AppendResultDTO


class UpdatesFeedSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = UpdatesFeedDTO


class ResyncSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = ResyncDTO


class DownloadUrlSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = DownloadUrlDTO


class UploadTicketSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = UploadTicketDTO


class TrashPurgeResultSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = TrashPurgeResultDTO


# ── Query-parameter envelopes ────────────────────────────────────────


class WorkspaceQuerySerializer(serializers.Serializer):
    """Common list-scope query: workspace_id is mandatory (400 when absent)."""

    workspace_id = serializers.UUIDField()


class DocumentListQuerySerializer(WorkspaceQuerySerializer):
    folder_id = serializers.UUIDField(required=False, allow_null=True)
    type = serializers.CharField(max_length=32, required=False)
    q = serializers.CharField(max_length=512, required=False)


# ── Folder requests ──────────────────────────────────────────────────


class FolderCreateSerializer(serializers.Serializer):
    workspace_id = serializers.UUIDField()
    name = serializers.CharField(max_length=255)
    parent_id = serializers.UUIDField(required=False, allow_null=True)


class FolderPatchSerializer(serializers.Serializer):
    """rename (name) = edit; move (parent_id, null = to root) = manage."""

    name = serializers.CharField(max_length=255, required=False)
    parent_id = serializers.UUIDField(required=False, allow_null=True)


# ── Document requests ────────────────────────────────────────────────


class DocumentCreateSerializer(serializers.Serializer):
    workspace_id = serializers.UUIDField()
    type = serializers.CharField(max_length=32)
    title = serializers.CharField(max_length=512)
    folder_id = serializers.UUIDField(required=False, allow_null=True)
    metadata = serializers.JSONField(required=False)
    # Optional initial body for editable types; absent -> spec.empty_body.
    body = serializers.CharField(required=False, allow_blank=True, trim_whitespace=False)


class DocumentPatchSerializer(serializers.Serializer):
    """title/metadata = edit; folder_id (null = to root) = manage."""

    title = serializers.CharField(max_length=512, required=False)
    metadata = serializers.JSONField(required=False)
    folder_id = serializers.UUIDField(required=False, allow_null=True)


# ── Journal requests ─────────────────────────────────────────────────


class UpdatesAppendSerializer(serializers.Serializer):
    updates = serializers.ListField(
        child=serializers.CharField(trim_whitespace=False), allow_empty=False
    )
    client_id = serializers.CharField(max_length=64, required=False, allow_blank=True)
    client_seq = serializers.IntegerField(required=False, allow_null=True)

    def validate_updates(self, value):
        decoded = []
        for item in value:
            try:
                decoded.append(base64.b64decode(item, validate=True))
            except Exception:
                raise serializers.ValidationError("updates must be base64 strings")
        return decoded


# ── Revision requests ────────────────────────────────────────────────


class NamedRevisionSerializer(serializers.Serializer):
    name = serializers.CharField(max_length=255)


# ── Trash requests ───────────────────────────────────────────────────


class TrashEmptySerializer(serializers.Serializer):
    workspace_id = serializers.UUIDField()
    # Absent -> purge everything trashed in the workspace.
    ids = serializers.ListField(child=serializers.UUIDField(), required=False)


# ── Upload requests ──────────────────────────────────────────────────


class UploadCreateSerializer(serializers.Serializer):
    workspace_id = serializers.UUIDField()
    title = serializers.CharField(max_length=512)
    folder_id = serializers.UUIDField(required=False, allow_null=True)
    mime_type = serializers.CharField(max_length=255, required=False, allow_blank=True)
    size_bytes = serializers.IntegerField(required=False, min_value=0)
    # Declared sha256 (hex) of the blob: finalize refuses an object that
    # hashes to anything else, so the ticket binds bytes, not just a slot.
    checksum = serializers.RegexField(
        r"^[0-9a-fA-F]{64}$", required=False, allow_blank=True
    )
