# Generated by Django 6.0.7 on 2026-08-09 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='docs.folder')),
            ],
            options={
                'db_table': 'docs_folder',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('head_seq', models.BigIntegerField(default=0)),
                ('snapshot_seq', models.BigIntegerField(default=0)),
                ('snapshot_key', models.CharField(blank=True, default='', max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='docs.folder')),
            ],
            options={
                'db_table': 'docs_document',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('auto', 'auto'), ('named', 'named')], default='auto', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('storage_key', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='docs.document')),
            ],
            options={
                'db_table': 'docs_revision',
                'ordering': ['-seq', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=512)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('key', models.CharField(max_length=512)),
                ('multipart_upload_id', models.CharField(blank=True, default='', max_length=512)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('finalized', 'finalized'), ('aborted', 'aborted')], default='pending', max_length=16)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='docs.document')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='docs.folder')),
            ],
            options={
                'db_table': 'docs_upload_session',
            },
        ),
        migrations.CreateModel(
            name='DocumentUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField()),
                ('payload', models.BinaryField()),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=64)),
                ('client_seq', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='docs.document')),
            ],
            options={
                'db_table': 'docs_update',
                'indexes': [models.Index(fields=['document', 'created_at'], name='docs_upd_doc_created')],
                'constraints': [models.UniqueConstraint(fields=('document', 'seq'), name='docs_update_doc_seq')],
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace_id', 'parent', 'name'), name='docs_folder_sibling_name'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace_id', 'folder'], name='docs_doc_ws_folder'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('document', 'seq', 'kind'), name='docs_revision_doc_seq_kind'),
        ),
    ]
