# Generated by Django 6.0.8 on 2026-09-01 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_uploadsession_checksum_uploadsession_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('accessed_at', models.DateTimeField(db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recents', to='docs.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_recents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docs_recent',
                'indexes': [models.Index(fields=['user', '-accessed_at'], name='docs_recent_user_seen')],
                'constraints': [models.UniqueConstraint(fields=('user', 'document'), name='docs_recent_user_document')],
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='docs.document')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='docs.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_stars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docs_star',
                'indexes': [models.Index(fields=['user', 'workspace_id'], name='docs_star_user_ws')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('folder__isnull', True)), models.Q(('document__isnull', True), ('folder__isnull', False)), _connector='OR'), name='docs_star_one_target'), models.UniqueConstraint(fields=('user', 'document'), name='docs_star_user_document'), models.UniqueConstraint(fields=('user', 'folder'), name='docs_star_user_folder')],
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.IntegerField()),
                ('source_seq', models.BigIntegerField(default=0)),
                ('storage_key', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='docs.document')),
            ],
            options={
                'db_table': 'docs_thumbnail',
                'constraints': [models.UniqueConstraint(fields=('document', 'tier'), name='docs_thumb_doc_tier')],
            },
        ),
    ]
