# Generated by Django 6.0.8 on 2026-09-02 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_drive_star_recent_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('subject_kind', models.CharField(choices=[('user', 'user'), ('ref', 'ref')], max_length=8)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ref', models.CharField(blank=True, default='', max_length=255)),
                ('level', models.CharField(choices=[('view', 'view'), ('edit', 'edit')], default='view', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='docs.document')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docs_access',
                'indexes': [models.Index(fields=['workspace_id', 'user_id'], name='docs_access_ws_user')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ref', ''), ('subject_kind', 'user'), ('user_id__isnull', False)), models.Q(('subject_kind', 'ref'), ('user_id__isnull', True), models.Q(('ref', ''), _negated=True)), _connector='OR'), name='docs_access_one_subject'), models.UniqueConstraint(condition=models.Q(('subject_kind', 'user')), fields=('document', 'user_id'), name='docs_access_doc_user'), models.UniqueConstraint(condition=models.Q(('subject_kind', 'ref')), fields=('document', 'ref'), name='docs_access_doc_ref')],
            },
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('level', models.CharField(choices=[('view', 'view'), ('edit', 'edit')], default='view', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('first_redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='docs.document')),
            ],
            options={
                'db_table': 'docs_link',
                'indexes': [models.Index(fields=['document', 'revoked_at'], name='docs_link_doc_live')],
            },
        ),
    ]
